version: "3.8"

services:
  website:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    restart: unless-stopped
    networks:
      - nginx-network

networks:
  nginx-network:
    driver: bridge
    external: true
